on: push
name: Build and Publish
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
        env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
        
    # - uses: actions/checkout@master
    # - name: Build a Docker image
    #   run: docker build -t react-app .
   
    # - name: Checkout
    #   uses: actions/checkout@master
    # - name: Publish Filter
    #   uses: actions/bin/filter@master
    #   with:
    #     args: branch master
    # - name: Build
    #   uses: actions/docker/cli@master
    #   with:
    #     args: build -t heroku .
    # - name: Login
    #   uses: actions/docker/login@master
    #   env:
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    # - name: Tag
    #   uses: actions/docker/tag@master
    #   with:
    #     args: heroku github/heroku --no-latest
    # - name: Publish
    #   uses: actions/docker/cli@master
    #   with:
    #     args: push github/heroku